# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:45:21+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel


class MultimediaItem(BaseModel):
    caption: Optional[str] = None
    copyright: Optional[str] = None
    format: Optional[str] = None
    height: Optional[int] = None
    subtype: Optional[str] = None
    type: Optional[str] = None
    url: Optional[str] = None
    width: Optional[int] = None


class RelatedUrl(BaseModel):
    suggested_link_text: Optional[str] = None
    url: Optional[str] = None


class Article(BaseModel):
    abstract: Optional[str] = None
    blog_name: Optional[str] = None
    byline: Optional[str] = None
    created_date: Optional[str] = None
    des_facet: Optional[List[str]] = None
    geo_facet: Optional[List[str]] = None
    headline: Optional[str] = None
    item_type: Optional[str] = None
    kicker: Optional[str] = None
    material_type_facet: Optional[str] = None
    multimedia: Optional[List[MultimediaItem]] = None
    org_facet: Optional[str] = None
    per_facet: Optional[List[str]] = None
    published_date: Optional[str] = None
    related_urls: Optional[List[RelatedUrl]] = None
    section: Optional[str] = None
    short_url: Optional[str] = None
    source: Optional[str] = None
    subsection: Optional[str] = None
    thumbnail_standard: Optional[str] = None
    title: Optional[str] = None
    updated_date: Optional[str] = None
    url: Optional[str] = None


class Source(Enum):
    all = 'all'
    nyt = 'nyt'
    iht = 'iht'
